CREATE TABLE `reclamaciones`.`tbl_proveedor` 
(`PROVEEDOR_ID` INT(6) NOT NULL , 
`RAZON_SOCIAL` VARCHAR(220) NOT NULL , 
`RUC` CHAR(11) NOT NULL , `CORREO` VARCHAR(60) NOT NULL , 
`TELEFONO` VARCHAR(120) NOT NULL , 
`ESTADO` CHAR(1) NOT NULL DEFAULT '1' ) 
ENGINE = InnoDB;